# -*- coding: utf-8 -*-
"""practica_orders_loc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIZKfBfZaP7vcs_IWFtprNTEb_Ft-q2A

** FUMCIONES AVANZADAS DE PANDAS**
"""

import pandas as pd
df = pd.read_csv('orders.csv')
df.abs

#mostrar la info tecnica del dataframe
df.info()

#mostrar los primeros registros
df.head(6)

#mostrr los ultimos 6 registros
df.tail(6)

"""funcion.**loc**"""

#seleccionar la columna "user_name"
#sintaxis df_loc(fila,columna)
df.loc[:,"user_name"]

#mostrar el registro de la fila 2
df.loc[1,:]

#user_name,product,order_id,order_date
df.loc[:,["order_id","user_name","product","order_date"]]

"""**CONDICIONES**:"""

#filtrar on una condicion y elegir las columnas
df.loc[df["city"]=="CDMX",["order_id","product","order_date","payment_method","city"]]

#filtrar con varias condiciones
#"category","discount"
#"categoria")="electronico y descuento"

x=(df["category"]=="Electronics")&(df['discount']>0.1)
df.loc[x,["order_id","product","discount","payment_method","category"]]

"""**FUNCION .ILOC**"""

#mostrar la columna "user_name" utilizando .iloc
#sintaxis df_loc(fila,columna)
df.iloc[:,3]

#mostar filas especificas del 0 al 5=rango
df.iloc[0:5]

#mostar filas especificas del 0,3,6
df.iloc[[0,3,6]]

#mostrar las 5 primers filas y 4 columnas
df.iloc[0:5,0:4]

"""**FUNCIONES QUERY=CONSULTAS**"""

#Consultaa simple para mostrar todos los registros de CDMX
df.query("city == 'CDMX'")

# Mostrar los registros que sean de CDMX,electronicos,y con un descuento igual a -1
df.query("city == 'CDMX' and category == 'Electronics' and discount == .1")

#mostrar los registros que sean de CDMX,GDL CON UN DESCUENTO IGUAL A -1
dis = 0.1
ciudades=["CDMX", "GDL"]
df.query("discount == @dis and city in @ciudades")

"""**AGREGACION**
.sum().mean().median().count().min().max()
"""

#Mostrar suma,promedio,mediana,min y max

df["net"].sum()

df["net"].mean()

df["net"].median()

df["net"].count()

df["net"].min(),df["net"].max()

#aplicamos las funciones suma,media,minimo y maximo a las columnas "unite_price","net"
df[["unit_price","net"]].agg(["sum","mean","min","max"])

#diferentes funciones
df.agg({
    "net" : ["sum","mean"],
    "unit_price" : ["max","min"],
    "discount" : ["mean","max"]
})