# -*- coding: utf-8 -*-
"""EJERCICIO ¿PEARSON O SPEARMAN?.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNaX3yTzKlCZRMXia8VTDAiXsDcQY4HT

**EJERCICIO ¿PEARSON O SPEARMAN?**
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar el dataset
df = pd.read_csv('estudiantes.csv')
df.info()

df.head()

#horas de estudio vs calificacion
plt.figure(figsize=(6,4))
plt.scatter(data=df, x="horas_estudio", y="calificacion")
plt.title("Horas de estudio vs Calificacion")
plt.xlabel("Horas de estudio")
plt.ylabel("Calificacion")
plt.show()

#horas de horas_sueno vs nivel_estres
plt.figure(figsize=(6,4))
plt.scatter(data=df, x="horas_sueno", y="nivel_estres")
plt.title("Horas de estudio vs nivel_estres")
plt.xlabel("horas_sueno")
plt.ylabel(" nivel_estres")
plt.show()

#uso_redes vs calificacion
plt.figure(figsize=(6,4))
plt.scatter(data=df, x="uso_redes", y="calificacion")
plt.title("uso_redes vs Calificacion")
plt.xlabel("uso_redes")
plt.ylabel("calificacion")
plt.show()

#pearson para las 3
pearson_estudio_calf = df['horas_estudio'].corr(df['calificacion'],method= 'pearson')
pearson_sueno_estres = df['horas_sueno'].corr(df['nivel_estres'],method= 'pearson')
pearson_redes_calf = df['uso_redes'].corr(df['calificacion'],method= 'pearson')
print("pearson: \n ")
print("horas de estudio vs calificacion ", pearson_estudio_calf)
print("horas de sueno vs nivel de estres ", pearson_sueno_estres)
print("horas en redes vs calificacion", pearson_redes_calf)

#spearman para las 3
spearman_estudio_calf = df['horas_estudio'].corr(df['calificacion'],method= 'spearman')
spearman_sueno_estres = df['horas_sueno'].corr(df['nivel_estres'],method= 'spearman')
spearman_redes_calf = df['uso_redes'].corr(df['calificacion'],method= 'spearman')
print("sperman: \n ")
print("horas de estudio vs calificacion ",spearman_estudio_calf)
print("horas de sueno vs nivel de estres ", spearman_sueno_estres)
print("horas en redes vs calificacion", spearman_redes_calf)

"""**Preguntas finales:**

¿Coinciden Pearson y Spearman? No exactamente,Aunque ambos muestran la misma tendencia (positiva o negativa), tienen valores distintos.

Coinciden más en estudio vs. calificación porque la relación es casi una línea recta perfecta.

Difieren más en sueño vs. estrés y redes vs. calificación, porque estas relaciones tienen más ruido o escalas de niveles (1 al 5), donde Spearman es más preciso al evaluar rangos. ¿Cambiarías tu decisión inicial?

¿Cambiarías tu decisión inicial?
Horas de estudio vs. Calificación: No, Mantengo Pearson por ser una relación lineal clara entre datos continuos.

Horas de sueño vs. Nivel de estrés: Sí, a Spearman, el estrés es una variable ordinal y la relación no es perfectamente lineal.

Uso de redes vs. Calificación: Sí, a Spearman. Es más robusto ante los outliers (valores atípicos) que presenta este par de variables.
"""