# -*- coding: utf-8 -*-
"""Regresion_Lineal2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzENu_pTuMSBbu6fsAy4XOY2LVQGQpWl

**REGRESIÓN LINEAL 2 - EJERCICIOS**

---

**Problema 2-EdadSeguros.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import statsmodels.api as sm

df = pd.read_csv("EdadSeguros.csv")

print(df.head())
print(df.info())

plt.figure(figsize=(7,5))

plt.scatter(df["Edad"], df["Costo"])

plt.xlabel("Edad del cliente")
plt.ylabel("Costo mensual del seguro")
plt.title("Relación entre Edad y Costo del Seguro")

plt.show()

X = df[['Edad']]
y = df['Costo']

modelo = LinearRegression()
modelo.fit(X,y)

pendiente = modelo.coef_[0]
intercepto = modelo.intercept_

print("Pendiente:", pendiente)
print("Intercepto:", intercepto)

print(f"Ecuación: Costo = {pendiente:.2f} * Edad + {intercepto:.2f}")

y_pred = modelo.predict(X)

X_sm = sm.add_constant(X)

modelo_sm = sm.OLS(y, X_sm).fit()

predicciones = modelo_sm.get_prediction(X_sm)

intervalos = predicciones.summary_frame(alpha=0.05)

print(intervalos.head())

plt.figure(figsize=(8,5))

plt.scatter(X, y, label="Datos reales")

plt.plot(X, y_pred, linewidth=2, label="Regresión lineal")

plt.xlabel("Edad")
plt.ylabel("Costo del seguro")
plt.title("Modelo de regresión: Edad vs Costo")

ecuacion = f"Costo = {pendiente:.2f} * Edad + {intercepto:.2f}"
plt.text(min(X.values), max(y), ecuacion)

plt.legend()

plt.show()

edades = pd.DataFrame({'Edad':[30,40,50,60]})

predicciones = modelo.predict(edades)

tabla_predicciones = pd.DataFrame({
    "Edad": edades["Edad"],
    "Costo_estimado": predicciones
})

tabla_predicciones