# -*- coding: utf-8 -*-
"""Regresion_lineal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKGg7PHkLzAmPnEg0kVtELo_8PpqoByW

**--------------REGRESIÓN LINEAL- EJERCICIOS-----------**

---

**PROBLEMA1-publicidadVentas.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("PublicidadVentas.csv")
df.head()

print(df.info())

X = df[['Inversion']]
y = df['Ventas']

modelo = LinearRegression()

modelo.fit(X, y)

pendiente = modelo.coef_[0]
intercepto = modelo.intercept_

print("Pendiente (m):", pendiente)
print("Intercepto (b):", intercepto)

print(f"Ecuación del modelo: Ventas = {pendiente:.2f} * Inversion + {intercepto:.2f}")

y_pred = modelo.predict(X)

mse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

print("Error Cuadrático Medio (MSE):", mse)
print("Coeficiente de Determinación (R²):", r2)

plt.figure(figsize=(8,5))

plt.scatter(X, y, label="Datos reales")

plt.plot(X, y_pred, linewidth=2, label="Línea de regresión")

plt.xlabel("Inversión en Publicidad (miles de dólares)")
plt.ylabel("Unidades Vendidas")
plt.title("Relación entre Inversión en Publicidad y Ventas")

ecuacion = f"Ventas = {pendiente:.2f} * Inversion + {intercepto:.2f}"
plt.text(min(X.values), max(y), ecuacion)

plt.legend()
plt.show()

def estimar_ventas(inversion):
    prediccion = modelo.predict([[inversion]])
    return prediccion[0]

estimar_ventas(5)