# -*- coding: utf-8 -*-
"""Regresion_Lineal3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kza3g3DPUJ8AkYb_WCS3x5k-IiQIKY6

**REGRESIÓN LINEAL 3 - EJERCICIOS**

**Problema 3-PracticaExamenes.csv**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv("PracticaExamenes.csv")

print("Primeras filas del dataset:")
print(df.head())

print("\nInformación del dataset:")
print(df.info())

print(df.columns)

plt.figure(figsize=(7,5))

plt.scatter(df["horas"], df["puntuacion"])

plt.xlabel("Horas de práctica semanal")
plt.ylabel("Puntuación del examen")
plt.title("Relación entre horas de práctica y puntuación")

plt.show()

X = df[['horas']]
y = df['puntuacion']

modelo = LinearRegression()

modelo.fit(X, y)

pendiente = modelo.coef_[0]
intercepto = modelo.intercept_

print("Pendiente:", pendiente)
print("Intercepto:", intercepto)

print(f"Ecuación: Puntuacion = {pendiente:.2f} * Horas + {intercepto:.2f}")

y_pred = modelo.predict(X)

r2 = r2_score(y, y_pred)

print("Coeficiente de determinación (R²):", r2)

plt.figure(figsize=(8,5))

plt.scatter(X, y, label="Datos reales")

plt.plot(X, y_pred, linewidth=2, label="Línea de regresión")

plt.xlabel("Horas de práctica")
plt.ylabel("Puntuación del examen")
plt.title("Regresión lineal: práctica vs puntuación")

ecuacion = f"Puntuacion = {pendiente:.2f} * Horas + {intercepto:.2f}"
plt.text(min(X.values), max(y), ecuacion)

plt.legend()

plt.show()

def predecir_puntuacion(horas):
    pred = modelo.predict([[horas]])
    return pred[0]

print("Puntuación esperada para 5 horas de práctica:", predecir_puntuacion(5))

for h in [2,4,6,8,10]:
    print(f"Horas: {h} -> Puntuación estimada: {predecir_puntuacion(h):.2f}")