# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XoanQgZ39FJKTVPo4GrjYC4EgVIqr2QM

**Parte 1: Carga y Exploración de Datos**
1. Carga de datos: Carga un archivo CSV (por ejemplo, `datos.csv`) utilizando `pandas`.
"""

import pandas as pd

df = pd.read_csv('datos1.csv')

"""2. Exploración básica: Muestra las primeras 5 filas, las últimas 5 filas, y un resumen estadístico de los datos"""

df.head()
df

df.describe()

"""3. Información del DataFrame: Muestra la información del DataFrame (tipos de datos, columnas, etc.)."""

df.info()

"""**Parte 2: Limpieza de Datos**
1. Muestra la cantidad de valores nulos y eliminar valores faltantes
"""

df.isnull().sum()

"""2. Rellenar valores faltantes: Rellena los valores faltantes con 0.

"""

df.fillna(0)

"""3. Eliminar columnas innecesarias: Elimina una columna que no sea relevante para el análisis."""

df = df.dropna()

"""**Parte 3: Filtrado y Selección de Datos**
1. Filtrar con múltiples condiciones: Filtra las filas que cumplan con múltiples condiciones.
"""

df_filtrado = df[(df["edad"] >= 18) & (df["edad"] <= 40)]
df_filtrado

"""2. Seleccionar columnas: Selecciona solo ciertas columnas para un nuevo DataFrame.

"""

df_seleccion = df[['edad', 'sexo']]
df_seleccion

"""**Parte 4: Operaciones y Agrupación**
1. Calcula la suma, media de una columna.
"""

suma_edad = df["edad"].sum()
media_edad = round(df["edad"].mean(), 2)

print("Suma de edades:", suma_edad)
print("Promedio de edad:", media_edad)

"""2. Agrupa los datos por una columna y calcula la media de otra columna para cada grupo."""

media_por_sexo = df.groupby('sexo')['edad'].mean()
media_por_sexo

"""3. Crea una tabla pivote para resumir los datos."""

df_ordenado = df.sort_values(by='edad', ascending=False)
df_ordenado.head()

"""**Ejercicio 5: Manipulación de Datos**
1. Ordenar datos: Ordena el DataFrame por una columna específica.
"""

df_ordenado = df.sort_values(by="edad")
df_ordenado.head()

df_ordenado = df.sort_values(by="edad", ascending=False)
df_ordenado.head()

"""**Ejercicio 6: Guardar Resultados**
1. Guardar DataFrame: Guarda el DataFrame modificado en un nuevo archivo CSV.
"""

df_ordenado.to_csv("datos_modificados.csv", index=False)

from google.colab import files
files.download("datos_modificados.csv")